[package]
name = "whistle"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
eyre = "0.6"
futures-util = "0.3"
alloy = { version = "0.5", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
hex-literal = "0.4"
chrono = "0.4"